name: TFState Backup

on:
  schedule:
    - cron: '30 14 * * 5'  # Every Friday at 8 PM IST (14:30 UTC)
  workflow_dispatch:       # Allows manual runs

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run tfstate backup script
        run: bash ./scripts/backup_tfstate.sh
